a=int(input("enter 1st number"))
b=int(input("enter 2nd number"))
print("sum is", a+b)
print("difference is", a-b)
print("product is", a*b)
print("quotient is", a/b)
print("remainder is", a%b)
